name: uccde
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy
  - scipy
  - scikit-image
  - opencv
  - tqdm
  - pillow
  - ffmpeg
  - pip
  - pip:
      - basicsr
      - facexlib
      - gfpgan
      - realesrgan
      - torch
      - torchvision
      - natsort
      - ffmpeg-python
